version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_faculdade
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: banco_servicos
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_faculdade
    restart: always
    ports:
      - "6379:6379"